"use client";

import {FormEvent,useState} from "react";

const SB_URL="https://uxbhhkoxcayjkbsxfabk.supabase.co";
const SB_KEY="sb_publishable_IvnK60RCaP2upVGhyijtCA_tkPOvocY";

async function loginAdmin(email:string,password:string){
  const r=await fetch(`${SB_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SB_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok||!d.access_token||!d.user?.id)throw new Error(d?.error_description||d?.msg||"Giriş başarısız.");
  const p=await fetch(`${SB_URL}/rest/v1/app_users?id=eq.${encodeURIComponent(d.user.id)}&select=role`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${d.access_token}`},cache:"no-store"});
  const rows=await p.json().catch(()=>[]);
  if(!p.ok||!Array.isArray(rows)||rows[0]?.role!=="admin")throw new Error("Bu bölüm yalnızca admin kullanıcılar içindir.");
  return {token:String(d.access_token),email:String(d.user.email||email)};
}

export default function Kurtarma(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [adminEmail,setAdminEmail]=useState("");const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 async function connect(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");try{const s=await loginAdmin(email.trim(),password);setAdminEmail(s.email);setPassword("");}catch(err:any){setMsg(err?.message||"Giriş başarısız.")}finally{setBusy(false)}}
 if(!adminEmail)return <main className="page"><div className="wrap"><a className="back" href="/">← Portala Dön</a><div className="loginCard"><div className="lock">🔐</div><h1>Acil Kurtarma Merkezi</h1><p>Bu bölüm yalnızca sistem yöneticilerine açıktır.</p><form onSubmit={connect}><input type="email" placeholder="Yönetici e-posta" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Şifre" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?"Doğrulanıyor...":"Admin Girişi"}</button></form>{msg&&<div className="msg">{msg}</div>}<small>Kullanıcı Yönetimi ekranındaki admin hesabınla giriş yap.</small></div></div><style>{styles}</style></main>;
 return <main className="page"><div className="wrap"><div className="top"><div><a className="back" href="/">← Portala Dön</a><h1>🛟 Acil Kurtarma Merkezi</h1><p>Uygulamalardan biri açılmadığında hangi sistemin etkilendiğini buradan takip edeceğiz.</p></div><div className="admin"><b>ADMIN</b><span>{adminEmail}</span><button onClick={()=>{setAdminEmail("");setEmail("");setMsg("")}}>Çıkış</button></div></div><div className="grid"><div className="card"><h2>⚡ Trafo Değişimi</h2><p>Kod ve veri kurtarma durumu</p><a href="https://balikesir-trafo-degisimi.vercel.app/api/health" target="_blank">Servis kontrolü →</a></div><div className="card"><h2>🖥️ SCADA Saha Kontrol</h2><p>Kod ve veri kurtarma durumu</p><a href="https://scada-saha-kontrol-vercel.vercel.app/api/health" target="_blank">Servis kontrolü →</a></div><div className="card"><h2>🎥 Görüntülü Teyit</h2><p>Kod ve veri kurtarma durumu</p><a href="https://goruntulu-teyit-v1.vercel.app/api/version" target="_blank">Servis kontrolü →</a></div></div><div className="note">Uygulama arayüzü açılmasa bile bu merkez Portal projesinde ayrı olarak çalışır. Kurtarma gerektiğinde son sağlam yedek veya son sağlam deployment üzerinden işlem yapılır.</div></div><style>{styles}</style></main>
}

const styles=`*{box-sizing:border-box}body{margin:0;background:#071426;font-family:Arial,Helvetica,sans-serif}.page{min-height:100vh;background:radial-gradient(circle at 50% -20%,#15395b,#071426 58%);color:#fff;padding:32px 18px}.wrap{width:min(980px,100%);margin:auto}.back{color:#fff;text-decoration:none}.loginCard{width:min(480px,100%);margin:8vh auto 0;background:linear-gradient(180deg,#10283f,#091b2d);border:1px solid #ffffff18;border-radius:20px;padding:28px;box-shadow:0 20px 55px #0005}.lock{font-size:34px}.loginCard h1{margin:10px 0 6px}.loginCard p{color:#a9bdd0;font-size:13px}.loginCard form{display:grid;gap:10px;margin-top:20px}.loginCard input{height:44px;border-radius:10px;border:1px solid #ffffff1c;background:#0b2035;color:#fff;padding:0 12px}.loginCard button{height:44px;border:0;border-radius:10px;background:#e8590c;color:#fff;font-weight:900;cursor:pointer}.loginCard small{display:block;color:#7890a8;margin-top:14px;font-size:10px}.msg{margin-top:12px;padding:10px;border-radius:10px;background:#7f1d1d55;color:#fecaca;font-size:11px}.top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.top h1{font-size:32px;margin:12px 0 8px}.top p{color:#a9bdd0}.admin{display:flex;align-items:center;gap:8px;background:#ffffff08;border:1px solid #ffffff14;padding:8px 10px;border-radius:12px}.admin b{font-size:8px;color:#86efac}.admin span{font-size:10px;color:#cbd8e7}.admin button{border:0;background:#7f1d1d55;color:#fecaca;border-radius:8px;padding:6px 9px;font-size:9px;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:22px}.card{background:#10283f;border:1px solid #ffffff18;border-radius:16px;padding:18px}.card h2{font-size:16px;margin:0 0 8px}.card p{color:#9fb2c5;font-size:12px}.card a{color:#93c5fd;text-decoration:none}.note{margin-top:18px;padding:16px;border-radius:14px;background:#ffffff08;border:1px solid #ffffff14;color:#cbd8e7;font-size:12px;line-height:1.6}@media(max-width:700px){.page{padding:20px 12px}.top{display:block}.admin{margin-top:14px;width:100%;justify-content:space-between}.grid{grid-template-columns:1fr}.top h1{font-size:25px}.loginCard{margin-top:4vh;padding:20px}}`;